// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axqqqpomxdjwrpkbfawl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4cXFxcG9teGRqd3Jwa2JmYXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NTUxOTEsImV4cCI6MjA2ODAzMTE5MX0.lje3XXCTUZL5-htXlEzuuxAWgWD-7tw3TC7ayuBslUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});